server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    dynamic:
      master: master
      strict: false
      druid:
        showSql: true
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        exceptionSorter: true
        testOnReturn: false
        poolPreparedStatements: true
        filters: stat,slf4j
        maxPoolPreparedStatementPerConnectionSize: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        useGlobalDataSourceStat: true
        filter:
          wall:
            config:
              multi-statement-allow: true
              none-base-statement-allow: true
      datasource:
        master:
          url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.db}?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
          username: ${mysql.user}
          password: ${mysql.pwd}

  security:
    type: security
    domain: localhost
  main:
    allow-circular-references: true
  data:
    redis:
      enabled: false
      host: localhost
      port: 6379
      password:
      connectTimeout: 10
  cache:
    type: simple

knife4j:
  enable: true
  openapi:
    title: 模板项目
    description: "模板项目"
    email: xiaoymin@foxmail.com
    url: https://docs.ngq.com
    version: v4.0

logging:
  level:
    org.springframework.security: trace

api:
  # 白名单
  whiteIps: 127.0.0.1
  # 流量限制，每s每ip最多支持请求数，需要启用Redis才能使用
  limitInSecond: 60