name: $T$Service
dir: service
comment: "服务接口"
imports:
  - $T$Entity
  - $T$DTO
  - $T$Query
  - com.liuqi.common.base.service.BaseService
template: "public interface $T$Service extends BaseService<$T$Entity, $T$DTO, $T$Query> {
  }"