server:
  port: 8080

application:
  security:
    ignored-urls: /favicon.ico,/test,/test/**/*,/doc.html,/webjars/**/*,/v3/api-docs/**/*,/v3/api-docs

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.db}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${mysql.user}
    password: ${mysql.pwd}
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

knife4j:
  enable: true
  openapi:
    title: 模板项目
    description: "模板项目"
    email: xiaoymin@foxmail.com
    url: https://docs.ngq.com
    version: v4.0