# 类生成配置

# 基础包
#basePackage: com.liuqi.base
# 表信息注解，只有被这个注解的类才处理；可以是TableName或者是Spring本身的Table
tableAnnotation: com.baomidou.mybatisplus.annotation.TableName
# 注释注解，用于生成类的注释
commentAnnotation: com.liuqi.common.annotations.Comment
# 是否生成liquibase，如果为true，那么会根据tableAnnotation中的表名生成建表语句，并添加在liquibase/master.xml中；（默认）
withLiquibase: true
# withLiquibase为true时生效；liquibase的生成语句保存文件，不配置则默认是liquibase/master.xml
liquibaseFile: liquibase/master.xml
# 前端界面配置模板
pageTemplate: page
# 需要生成的类列表，每个类列表需要对应一个同名的yaml配置文件
classes:
  - dto
  - addReq
  - updateReq
  - query
  - mapper
  - service
  - serviceImpl
  - controller